# ===================================================================
# Configuration for the "test" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.application.tech/profiles/
# More information on configuration properties: https://www.application.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard app properties.
# ===================================================================

eureka:
    instance:
        prefer-ip-address: true
    client:
        service-url:
            defaultZone: http://admin:${application.registry.password}@localhost:8761/eureka/

server:
    port: 8081

    mail:
        host: localhost
        port: 25
        username:
        password:

application:
    mail: # specific application mail property, for standard properties see MailProperties
        from: skygge_validate@localhost
        base-url: http://127.0.0.1:8082
# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the applicationProperties above
#
# More documentation is available at:
# https://www.application.tech/common-application-properties/
# ===================================================================

# application:
