eureka:
    client:
        enabled: false
        healthcheck:
            enabled: true
        fetch-registry: true
        register-with-eureka: true
        instance-info-replication-interval-seconds: 10
        registry-fetch-interval-seconds: 10
    instance:
        appname: skygge_validate
        instanceId: skygge_validate:${random.value}
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 10
        status-page-url-path: ${management.endpoints.web.base-path}/info
        health-check-url-path: ${management.endpoints.web.base-path}/health
        metadata-map:
            zone: primary # This is needed for the load balancer
            version: #project.version#
            git-version: ${git.commit.id.describe:}
            git-commit: ${git.commit.id.abbrev:}
            git-branch: ${git.branch:}

application:
    clientApp:
        name: 'skygge_validate'
    registry:
        password: admin
    security:
        authentication:
            jwt:
                # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
                base64-secret: NDhjNjk1NTM3NWRlNjc1NDMwZjllNWFiMmVlYjQ4NzViYzY4MmY5ZWY2MzZhMzNiMTYxYmNlYjJkMWYwNDk0NDBlNDYwZThjMmFmNzAyNTQyOWYxMDhkM2QxYTQ3ZDFjM2I5YWU4YWVjOGRhNDc3MWE5OTExMzUyMjI3MDlmZWM=
                # Token is valid 24 hours
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000
    mail:
        from: skygge_validate@localhost
    swagger:
        default-include-pattern: /api/.*
        title: skygge_validate API
        description: skygge_validate API documentation
        version: 0.0.1
        terms-of-service-url:
        contact-name:
        contact-url:
        contact-email:
        license:
        license-url:
        path: /api/v2/api-docs

cloud:
    config:
        uri: http://admin:${application.registry.password}@localhost:8761/config
        # name of the config server's property source (file.yml) that we want to use
        name: skygge_validate
        profile: prod # profile(s) of the property source
        label: master # toggle to switch to a different version of the configuration as stored in git
        # it can be set to any label, branch or commit of the configuration source Git repository
